export const ACCESS_TOKEN = "access";
export const REFRESH_TOKEN = "refresh";
export const listOfTeam = {
    'Atlanta Hawks' : 'Hawks',
    'Boston Celtics' : 'Celtics',
    'Cleveland Cavaliers' : 'Cavaliers',
    'New Orleans Pelicans' : 'Pelicans',
    'Chicago Bulls' : 'Bulls',
    'Dallas Mavericks' : 'Mavericks',
    'Denver Nuggets' : 'Nuggets',
    'Golden State Warriors' : 'Warriors',
    'Houston Rockets' : 'Rockets',
    'Los Angeles Clippers' : 'Clippers',
    'Los Angeles Lakers' : 'Lakers',
    'Miami Heat' : 'Heat',
    'Milwaukee Bucks' : 'Bucks',
    'Minnesota Timberwolves' : 'Timberwolves',
    'Brooklyn Nets' : 'Nets',
    'New York Knicks' : 'Knicks',
    'Orlando Magic' : 'Magic',
    'Indiana Pacers' : 'Pacers',
    'Philadelphia 76ers' : '76ers',
    'Phoenix Suns' : 'Suns',
    'Portland Trail Blazers' : 'Blazers',
    'Sacramento Kings' : 'Kings',
    'San Antonio Spurs' : 'Spurs',
    'Oklahoma City Thunder' : 'Thunder',
    'Toronto Raptors' : 'Raptors',
    'Utah Jazz' : 'Jazz',
    'Memphis Grizzlies' : 'Grizzlies',
    'Washington Wizards' : 'Wizards',
    'Detroit Pistons' : 'Pistons',
    'Charlotte Hornets' : 'Hornets'
}